Feature/husky config
woopul/lingo-match pull request #1
Opened 2023-04-23 18:33 UTC by mrguisher

basic husky config including commit msg validation, lint and validate branch name on pre-commit hook

2023-04-24 22:40 UTC, woopul requested changes

2023-04-25 13:58 UTC, mrguisher commented on README.md
> +### Branch names
> Is it really necessary ? - branches checks from my experience are redundant , I will suggest to use plugin from jira to simply create branch from that and not check if name is propper. What do you think?

ok we can do without it then

2023-04-25 14:02 UTC, mrguisher commented on README.md
> +### Branch names
so in order not to be overwhelmed by numerous plugins we could start every branch with task number as a prefix instead of feature/bug etc 
how about that?

2023-04-25 20:19 UTC, woopul commented on README.md
> +### Branch names
Sure, but this is actually already build in feature in jira -


![obraz](https://user-images.githubusercontent.com/21220135/234393088-c04b7f96-a855-481b-89d2-9e1568eb39ec.png)

And anyway - for me it's not that valid as I do not actually care how branches will be named as long as it will have some sort of information inside about what topic is this. If for you it is iportant I will comply 👍 living thumb for ya to decide

2023-04-25 20:19 UTC, woopul approved these changes

2023-04-27 19:54 UTC, merged